"""
test_combined_acetyl_to_sorbic.py
=================================

End-to-end demo: acetyl-CoA → TAL → sorbic acid through a single
combined network.

Four networks are involved:

  1. BIO          : acetyl-CoA + malonyl-CoA → TAL via the polyketide
                    chain (rule1118, rule0087, rule0891). Generated by
                    our wrapper, which reroutes to DORAnet's native
                    enzymatic expansion.

  2. CHEM FORWARD : forward chem from TAL. Reaches the first half of
                    the TAL → sorbic chain (down to HMP / saturated
                    lactone) with the C6/O3 atom cap.

  3. CHEM RETRO   : retro chem from sorbic acid. Reaches the second
                    half (PSA, open-chain hexenoate, hydroxy-hexenoate)
                    walking backward from sorbic acid toward TAL.

  4. COMBINED     : pretreat_networks([bio, chem_fwd, chem_retro],
                    starters=[acetyl-CoA], helpers=[malonyl-CoA, O,
                    H2]) merges all three. DORAnet auto-flips retro
                    reactions to forward direction before merging.

The two chem halves meet in the middle because forward-from-TAL stops
at HMP and retro-from-sorbic walks back to HMP/PSA — together they
cover the full TAL → sorbic chain. Then pathway_finder traces
acetyl-CoA → sorbic acid through the unified network.

Finally visualize_pathways renders the combined graph as a single
HTML DAG.
"""

import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))
sys.stdout.reconfigure(encoding="utf-8")

from rdkit import RDLogger
RDLogger.DisableLog("rdApp.*")

from network_generation import generate_network_tal
from pathway_tools import load_pathways_from_file, parse_reaction_string
from recipe_rankers import ForwardProductTanimotoRanker, FeedstockProximityRanker
from visualize_pathways import visualize_pathways
from doranet.modules.post_processing.post_processing import (
    pretreat_networks,
    pathway_finder,
)


ACETYL_COA = (
    "CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(O)OP(=O)(O)"
    "OC[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1OP(=O)(O)O"
)
MALONYL_COA = (
    "OC(=O)CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(O)OP(=O)(O)"
    "OC[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1OP(=O)(O)O"
)
TAL         = "Cc1cc(O)cc(=O)o1"
SORBIC_ACID = "CC=CC=CC(=O)O"          # stereo-less form (DORAnet's
                                       # Dehydration of Alcohol drops E/Z)

POLYKETIDE_WHITELIST = frozenset({
    "rule1118",   # Claisen 1
    "rule0087",   # Claisen 2
    "rule0891",   # cyclization
})

JOB_NAME = "combined_acetyl_to_sorbic"
BIO_GEN       = 3
CHEM_FWD_GEN  = 4   # forward from TAL — gets us through the first half
CHEM_RETRO_GEN = 4  # retro from sorbic acid — covers the second half


def write_smi(path, lines):
    with open(path, "w") as f:
        for s in lines:
            f.write(s + "\n")


def main():
    print("=" * 70)
    print(" COMBINED  acetyl-CoA  →  TAL  →  sorbic acid")
    print("=" * 70)

    write_smi("combined_bio_starter.smi",           [ACETYL_COA, MALONYL_COA])
    write_smi("combined_chem_fwd_starter.smi",      [TAL])
    write_smi("combined_chem_fwd_helpers.smi",      ["O", "[H][H]"])
    write_smi("combined_chem_retro_starter.smi",    [SORBIC_ACID])
    write_smi("combined_chem_retro_helpers.smi",    ["O", "[H][H]"])

    overall_t0 = time.time()

    # ----- STEP 1: bio expansion ---------------------------------------
    print(f"\n[1/5] Bio expansion: acetyl-CoA + malonyl-CoA → TAL")
    print(f"      polyketide whitelist ({len(POLYKETIDE_WHITELIST)} rules), gen={BIO_GEN}")
    t0 = time.time()
    bio_net = generate_network_tal(
        job_name=f"{JOB_NAME}_bio",
        starters="combined_bio_starter.smi",
        gen=BIO_GEN,
        direction="forward",
        max_rxn_thermo_change=15.0,
        max_atoms=None,
        allow_multiple_reactants="default",
        include_chem=False,
        include_bio=True,
        bio_allow_multiple_reactants=True,
        bio_whitelist=POLYKETIDE_WHITELIST,
        targets=TAL,
    )
    print(f"      finished in {time.time()-t0:.1f}s  |  "
          f"{len(bio_net.mols)} mols, {len(bio_net.rxns)} reactions")

    # ----- STEP 2a: chem forward from TAL ------------------------------
    print(f"\n[2/6] Chem expansion forward: TAL → ... (gen={CHEM_FWD_GEN}, cartesian)")
    t0 = time.time()
    chem_fwd_net = generate_network_tal(
        job_name=f"{JOB_NAME}_chem_fwd",
        starters="combined_chem_fwd_starter.smi",
        helpers="combined_chem_fwd_helpers.smi",
        gen=CHEM_FWD_GEN,
        direction="forward",
        molecule_thermo_calculator=None,
        max_rxn_thermo_change=15.0,
        max_atoms={"C": 6, "O": 3, "N": 0, "S": 0},
        max_molecular_weight=150,
        strategy="cartesian",
        include_chem=True,
        include_bio=False,
    )
    print(f"      finished in {time.time()-t0:.1f}s  |  "
          f"{len(chem_fwd_net.mols)} mols, {len(chem_fwd_net.rxns)} reactions")

    # ----- STEP 2b: chem retro from sorbic acid ------------------------
    print(f"\n[3/6] Chem expansion retro: sorbic acid ← ... (gen={CHEM_RETRO_GEN})")
    t0 = time.time()
    chem_retro_net = generate_network_tal(
        job_name=f"{JOB_NAME}_chem_retro",
        starters="combined_chem_retro_starter.smi",
        helpers="combined_chem_retro_helpers.smi",
        gen=CHEM_RETRO_GEN,
        direction="retro",
        molecule_thermo_calculator=None,
        max_rxn_thermo_change=15.0,
        max_atoms={"C": 6, "O": 3, "N": 0, "S": 0},
        max_molecular_weight=150,
        strategy="priority_queue",
        targets=TAL,
        recipe_ranker=FeedstockProximityRanker([TAL]),
        beam_size=200,
        include_chem=True,
        include_bio=False,
    )
    print(f"      finished in {time.time()-t0:.1f}s  |  "
          f"{len(chem_retro_net.mols)} mols, {len(chem_retro_net.rxns)} reactions")

    # ----- STEP 3: combine all three -----------------------------------
    # Helpers passed: malonyl-CoA (free substrate for bio Claisens),
    # water + H2 (chem dehydrations/reductions). Bio cofactors auto-
    # added by pretreat_networks because of the JN1224MIN bio_rxn_names
    # patch in pathway_tools.py. The retro chem reactions get auto-
    # flipped to forward direction by pretreat_networks.
    print(f"\n[4/6] Combining bio + chem(fwd) + chem(retro) networks")
    t0 = time.time()
    pretreat_networks(
        networks=[bio_net, chem_fwd_net, chem_retro_net],
        starters=[ACETYL_COA],
        helpers=[MALONYL_COA, "O", "[H][H]"],
        total_generations=BIO_GEN + CHEM_FWD_GEN + CHEM_RETRO_GEN,
        job_name=JOB_NAME,
    )
    print(f"      combined in {time.time()-t0:.1f}s")

    # ----- STEP 4: trace pathways --------------------------------------
    print(f"\n[5/6] Tracing pathways: acetyl-CoA → sorbic acid")
    t0 = time.time()
    pathway_finder(
        starters=[ACETYL_COA],
        helpers=[MALONYL_COA, "O", "[H][H]"],
        target=[SORBIC_ACID],
        search_depth=BIO_GEN + CHEM_FWD_GEN + CHEM_RETRO_GEN,
        max_num_rxns=15,
        job_name=JOB_NAME,
    )
    print(f"      pathway_finder finished in {time.time()-t0:.1f}s")

    try:
        pathways = load_pathways_from_file(JOB_NAME)
    except FileNotFoundError:
        print("\nNo pathway file written.")
        return
    if not pathways:
        print("\nNo pathways found through the combined network.")
        return

    print(f"\n[SUCCESS] {len(pathways)} pathway(s) acetyl-CoA → sorbic acid")
    for i, p in enumerate(pathways[:5], 1):
        print(f"\n  Pathway {i}  ({p.num_steps} steps):")
        for j, rxn in enumerate(p.reactions, 1):
            parsed = parse_reaction_string(rxn)
            short_reas = [r if len(r) < 40 else r[:37] + "..." for r in parsed["reactants"]]
            short_pros = [pp if len(pp) < 40 else pp[:37] + "..." for pp in parsed["products"]]
            arrow = " + ".join(short_reas) + "  ->  " + " + ".join(short_pros)
            print(f"    Step {j}. [{parsed['op_name']}]")
            print(f"             {arrow}")

    # ----- STEP 5: visualize -------------------------------------------
    print(f"\n[6/6] Rendering combined visual graph...")
    html_path = visualize_pathways(
        job_name=JOB_NAME,
        starter_smiles=ACETYL_COA,
        target_smiles=SORBIC_ACID,
        starter_label="acetyl-CoA",
        target_label="sorbic acid",
        # malonyl-CoA is a real co-substrate (not a hidden cofactor) —
        # passed via extra_labels so it gets a human-readable label and
        # is never hidden, even though its skeleton looks cofactor-ish.
        # Helpers stay as the actual hidden molecules (water + H2).
        helpers=["O", "[H][H]"],
        pathway_filter="all",
        extra_labels={MALONYL_COA: "malonyl-CoA"},
    )
    print(f"      {html_path}")
    print(f"\nTotal runtime: {time.time() - overall_t0:.1f}s")


if __name__ == "__main__":
    main()
